### PR TITLE
[⚠️ WIP ⚠️] Api dev

### LINKED ISSUE #35: expanding api & adding tokens
so currently the limited repldex api doesn't have any tokens, and no way to ratelimit, or have restricted access, i suggest that using mongo db to store a token and there permissions, the permissions would be a list with all the permissions, and it would also store meta data in other properties, use as a ratelimit, or if it's request use a cache or not. These could also be controlled thru the admin panel.

### PR DESCRIPTION
**Pull request by Codemonkey51**
----------------

# ⚠️ WARNING THIS IS A WORK IN PROGRESS DO NOT MERGE ⚠️
----------------
Closes #35

Api changes

# progress:

- [x] api docs
- [ ] serve api docs on site 
- [ ] add tokens
- [ ] store tokens in db 
- [ ] token permissions 
- [ ] ratelimit's (maybe)
- [ ] more api paths (edit, create entries)
- [ ] api caching
- [ ] non token paths
- [ ] easy permissions extendability
- [ ] admin panel for tokens

### CODE REVIEW

**Comment by Codemonkey51** [comment]
Once this is done I think I'll make server into its own "module" and start isolating different parts into like server.api, server.routes, and server.admin, and each can export a route def object, also  commonly used functions could be in server.utils @mat-1 @jetstream0 

Tho this should prob be finished + merged first

**Comment by Codemonkey51** [comment]
Apparently sub apps are a thing 🤦

**Comment by jetstream0** [comment]
Any updates?

**Comment by Codemonkey51** [comment]
> Any updates?

Yep, I'm going to yet this branch and make a new one off of master, then ill apply theese changes to it. Then actually finish it

**Comment by Codemonkey51** [comment]
This is outdated, and changed nothing, a new branch based on master should be made.

**Pull request closed without merging**
