### PR TITLE
merge stuff I forgot to before

### PR DESCRIPTION
**Pull request by mat-1**

### CODE REVIEW

**Review by Codemonkey51 — APPROVED** [review]
This looks good!

**Comment by Codemonkey51** [comment]
Something just broke @mat-1 repldex is 500'ing I'll check it out

**Comment by Codemonkey51** [comment]
Fixed i think

**Comment by Codemonkey51** [comment]
Port issues and it needed a restart

**Comment by mat-1** [comment]
oof ok i didn't bother testing it myself because i didn't think it'd break anything

**Comment by Codemonkey51** [comment]
Lol it's just repldex down now

**Pull request merged**
