### PR TITLE
only admin route decorator

### PR DESCRIPTION
**Pull request by Codemonkey51**
Instead of invoking the function during admin only routes I made it a decorator, so you can just add it and be done with it.

### CODE REVIEW

**Comment by Codemonkey51** [comment]
One sec imma fix the tabs + indent errors

**Comment by Codemonkey51** [comment]
> you should rename adminOnly to admin_only for consistency 👍

Ok

**Comment by mat-1** [comment]
btw you misspelled functools in the import lol

**Comment by Codemonkey51** [comment]
> btw you misspelled functools in the import lol

oof ok I'll fix that to

**Comment by Codemonkey51** [comment]
Need to fix tabs again

**Comment by Codemonkey51** [comment]
@mat-1 fixed all errors

**Pull request merged**
