### PR TITLE
CSS Redesign

### LINKED ISSUE #66: Frontend Rework/Redesign (CSS)
The ReplDex frontend (website) hasn't seen any changes in quite a while, and I think it could use a lot of updating & reworking. I'd be down to work on this, as I've gotten a lot better at CSS the past few months (I still use frameworks cuz I'm lazy) and have quite a few ideas for good changes to how users interact with entries on ReplDex, editor or not.

I also wanna ask if it's okay to work with a CSS framework or if the CSS should be custom. (I was thinking about using [Bulma](https://bulma.io), because, again, I'm lazy).

If you have suggestions feel free to let me know =P (I'll include an ss of a prototype later or smth)

### PR DESCRIPTION
**Pull request by IreTheKID**
I've started to redesign the Repldex frontend pages by adding a unified navbar and small hero, along with a cleanup of the Index page. Most of the base classes are stuff I've written myself, but the columns and media queries are `CTRL+C` & `CTRL-V`'d cuz making responsive CSS is a pain >.<

I also plan to redesign the entry pages:

+ Show contributor PFPs
+ Make entry text centered (vertically)
+ Update diff pages to be more clear
+ Clean up buttons (Login, New/Edit Entry, etc.)

You can find what I've done so far at [DexCSS](https://dexcss.irethekid.repl.co/). (*The API broke so no entries =P*)

Closes #66

### CODE REVIEW

**Comment by Codemonkey51** [comment]
@IreTheKID i got this when visiting:
> # Internal Server Error
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by IreTheKID** [comment]
@Codemonkey51 Because the API broke :|

**Comment by Codemonkey51** [comment]
@IreTheKID Found the api error in repldex, am going to pr a patch rn

**Comment by IreTheKID** [comment]
Thanks!

**Comment by Codemonkey51** [comment]
@IreTheKID waiting for #73 to go thru (needs to be reviewed)

**Comment by IreTheKID** [comment]
Here's what I have so far!

### Old ReplDex Index Page:

Screenshot 2021-01-08 at 1.34.08 PM

### New ReplDex Index Page:
Screenshot 2021-01-08 at 1.34.27 PM

**Comment by IreTheKID** [comment]
The entry boxes are a bit wonky (image sizing and title centering) but it's a WIP so I'll fix it later.

**Comment by IreTheKID** [comment]
Just finalized entry boxes and text wrapping (floats are a pain) 
image

**Pull request closed without merging**
