### PR TITLE
Add substitutions

### PR DESCRIPTION
**Pull request by jetstream0**

### CODE REVIEW

**Comment by Codemonkey51** [comment]
wait cant you directly commit?

**Review by mat-1 — CHANGES_REQUESTED** [review]
You should make make the style of the code more pythonic:
- spaces after hash signs
- spaces after colons
- single quotes rather than double quotes
- shorter lines (newlines after commas)

**Comment by jetstream0** [comment]
pls dont accept yet, thanks
also mat
spaces after hash signs, sure why not
spaces after colons sure
single quotes rather than double quotes? too much work it really doesnt matter
shorter lines means a huge chunk of the code is one dictionary, which is bad

**Comment by jetstream0** [comment]
pls review

**Comment by mat-1** [comment]
tbh it might be even better to have the json in its own file

**Comment by Codemonkey51** [comment]
Ye maybe in config folder (or db but prob not)

**Comment by jetstream0** [comment]
ok sure will do that later

**Comment by jetstream0** [comment]
Done, please make sure it doesnt break anything

**Review by Codemonkey51 — CHANGES_REQUESTED** [review]
this should be moved in its own folder like config/substitutions.json so it doesn't clutter the config.json file

**Comment by Codemonkey51** [comment]
Wait @jetstream0 want to merge this branch to master after this is merged because after it gets its own config file it should be good to go, also once the pr from database-translations to master is made we can make sure it passes the checks

**Pull request merged**
