### PR TITLE
📝 IDEA: use Gitmoji

### PR DESCRIPTION
**Pull request by Codemonkey51**
Seems like a cool idea/way to easily see what a request does

### CODE REVIEW

**Comment by Codemonkey51** [comment]
@mat-1 @minx28 @jetstream0 what do think about this?

**Comment by Codemonkey51** [comment]
Oof commit name spelling error

**Comment by mat-1** [comment]
Looks like a pointless gimmick that makes everything harder for everyone

**Comment by Codemonkey51** [comment]
> Looks like a pointless gimmick that makes everything harder for everyone

Ok :/ I can close this now

**Pull request closed without merging**
