### PR TITLE
Grammar Checking

### PR DESCRIPTION
**Pull request by minx28**
Every entry now has `grammar` field - when I edit an entry that gets set to true, otherwise it gets set to false

### CODE REVIEW

**Review by leon332157 — APPROVED** [review]

**Comment by mat-1** [comment]
Is this really necessary? Just tell people to run their entries through grammarly or something before posting them lol

**Comment by frissyn** [comment]
This seems pretty redundant to me tbh, surely there's a better way to go about grammar checking for entries than this. And who's to say that @minx28 himself won't make a grammar mistake?

**Review by Codemonkey51 — DISMISSED** [review]
@frissyn brings up a good point. It should be a checkbox and should apply to all admins, not just minx. Assuming that grammar is correct because of who edited it is not a good idea

**Review by mat-1 — APPROVED** [review]

**Comment by Codemonkey51** [comment]
What is the point of edited_by_minx now? 
edited_by_codemonkey51 when?

**Comment by minx28** [comment]
codemonkey51 is incapable of doing good grammar and so if an entry is edited by him that's a bad thing

**Comment by Codemonkey51** [comment]
> codemonkey51 is incapable of doing good grammar and so if an entry is edited by him that's a bad thing

edited_by_codemonkey51 should make it alert minx

**Comment by minx28** [comment]
> edited_by_codemonkey51 should make it alert minx
this tbh

**Comment by Codemonkey51** [comment]
> > edited_by_codemonkey51 should make it alert minx
> 
> this tbh

~~it will spam ur dm's~~

**Comment by minx28** [comment]
> it will spam ur dm's

😳

**Comment by minx28** [comment]
in the meantime, please just approve this pr

**Comment by Codemonkey51** [comment]
> in the meantime, please just approve this pr

~~I'll think about it~~

**Comment by minx28** [comment]
haha gotcha. i just dismissed ur requested changes lmao

**Comment by Codemonkey51** [comment]
> haha gotcha. i just dismissed ur requested changes lmao

I just did it but it didn't go thru

**Comment by Codemonkey51** [comment]
> haha gotcha. i just dismissed ur requested changes lmao

I just did it but it didn't go thru

**Pull request merged**
