### PR TITLE
Cleanup and Reformat Code Style

### PR DESCRIPTION
**Pull request by IreTheKID**
It's pretty hard to contribute to a project with messy code, so I went through and formatted all the `.py` files with `black` and then, **by hand** went through and made some convention fixes. 

I don't mean to be that guy, whining about spaces over tabs and single-quotes vs. double-quotes, but, going through this project and trying to figure what was going on was quite a pain =P (@Codemonkey51 and @minx28 I'm lookin' at you)

The diff is pretty huge, but it was a lot more work than `black *`, so I guess it's worth it.

### CODE REVIEW

**Comment by Codemonkey51** [comment]
Nice! Once the tests pass this should be good to merge

**Comment by mat-1** [comment]
tabs over spaces and single quotes over double quotes >:(((

**Comment by jetstream0** [comment]
Did this replace tabs with spaces?

**Review by Codemonkey51 — CHANGES_REQUESTED** [review]
mat says: "tabs over spaces and single quotes over double quotes >:((("

**Comment by IreTheKID** [comment]
I change my settings on repl.it to replace my tabs with 4 spaces so... ¯\\\_(ツ)\_/¯

Anyways, if you despise using spaces so much, you can just `black` it before committing or smth idk =P

**Comment by IreTheKID** [comment]
> If your editor is configured to use tabs for Python indentation, that means you are unable to meaningfully contribute to any open-source software, including Python itself.

I'm not against tabs or anything, I **use** tabs, but, even if it's just for the sake of cleanliness, the GitHub source code should stick to spaces.

**Comment by mat-1** [comment]
This pr is very similar to #63 btw

**Comment by IreTheKID** [comment]
(#63) Addresses code structure, and I'm talking about code **style**. Don't be a weirdo @mat-1 :/

**Comment by mat-1** [comment]
yeah but both prs change the code style

**Comment by IreTheKID** [comment]
¯\\\_(ツ)\_/¯

**Comment by IreTheKID** [comment]
OK, just added an auto styling bash script to run before commits and whatnot. Now you can do whatever you want with the code (use braces for all I care) and run `bash clean.sh` to clean it up for the commit.

```bash
find . -name "*.py" -print0 | while read -d $'\0' file
do
    python -m black "$file" --fast
done
```

**Comment by IreTheKID** [comment]
Well since (#63) passed there's no point in merging this so I'll close it :|

**Pull request closed without merging**
