### PR TITLE
Reformat code using yapf

### PR DESCRIPTION
**Pull request by mat-1**
Can y'all make sure this doesn't break anything?

### CODE REVIEW

**Comment by Codemonkey51** [comment]
@mat-1 How about only adding the config, then styling all the files *after* it gets merged into master

**Comment by mat-1** [comment]
wait there's some other things i forgot to format don't merge this

**Comment by Codemonkey51** [comment]
Ummm, I was saying wait till after it's merged to format, so it's easier to deal with all the conficts :/

**Review by Codemonkey51 — CHANGES_REQUESTED** [review]
Remove the formatted files pls, it will make it easier to fix conflicts

**Comment by mat-1** [comment]
ok i give up trying to make yapf work how i want it to, im gonna format manually

**Comment by Codemonkey51** [comment]
Why not use black?

**Pull request closed without merging**
