### PR TITLE
Hi please add me to editors.txt uwu please accept uwu lol

### PR DESCRIPTION
**Pull request by sourcerose**
:)

### CODE REVIEW

**Comment by Codemonkey51** [comment]
ya know what...

**Comment by Codemonkey51** [comment]
no

**Comment by sourcerose** [comment]
oof

**Comment by sourcerose** [comment]
that sucks

**Comment by Codemonkey51** [comment]
lol

**Comment by sourcerose** [comment]
lol its live

**Review by Codemonkey51 — CHANGES_REQUESTED** [review]
remove ur self and ill merge

**Comment by Codemonkey51** [comment]
closing & locking bai apply for editor here: https://forms.gle/S2LV2KkKFnAarmMB9

**Comment by sourcerose** [comment]
no u

**Comment by Codemonkey51** [comment]
last

**Pull request closed without merging**
