### PR TITLE
Fix pep8 warnings

### LINKED ISSUE #46: fix flake8 warnings
fix the like **1700** flake8 warnings, maybe use black to fix styling

### PR DESCRIPTION
**Pull request by mat-1**
Fixed the majority of pep8 warnings and other miscellaneous formatting issues. Closes #46

### CODE REVIEW

**Comment by Codemonkey51** [comment]
Want to auto black the code like every day?

**Comment by Codemonkey51** [comment]
On a cron

**Comment by Codemonkey51** [comment]
We still have like 1460 warnings lmao

**Comment by mat-1** [comment]
Black is in beta and doesn't format exactly how I want it to. The remaining warnings are tab warnings, I'll ignore those in a minute

**Comment by Codemonkey51** [comment]
Oh ok

**Pull request merged**
